package dev.vdbroek.nekos.ui.theme

import androidx.compose.ui.graphics.Color

object NekoColors {
    val blue200 = Color(0xFF90CAF9)
    val blue500 = Color(0xFF2196F3)
    val blue700 = Color(0xFF1976D2)

    val darkCard = Color(0xFF292E35)

    val dark = Color(0xFF21252b)
    val light = Color(0xFFEEEEEE)
    val info = Color(0xFF209CEE)
    val success = Color(0xFF23D160)
    val warning = Color(0xFFFFDD57)
    val danger = Color(0xFFFF3860)

    val md_theme_light_primary = Color(0xFF00639a)
    val md_theme_light_onPrimary = Color(0xFFffffff)
    val md_theme_light_primaryContainer = Color(0xFFcbe5ff)
    val md_theme_light_onPrimaryContainer = Color(0xFF001d32)
    val md_theme_light_secondary = Color(0xFF51606f)
    val md_theme_light_onSecondary = Color(0xFFffffff)
    val md_theme_light_secondaryContainer = Color(0xFFd5e4f6)
    val md_theme_light_onSecondaryContainer = Color(0xFF0e1d2a)
    val md_theme_light_tertiary = Color(0xFF67587a)
    val md_theme_light_onTertiary = Color(0xFFffffff)
    val md_theme_light_tertiaryContainer = Color(0xFFefdbff)
    val md_theme_light_onTertiaryContainer = Color(0xFF221533)
    val md_theme_light_error = Color(0xFFba1b1b)
    val md_theme_light_errorContainer = Color(0xFFffdad4)
    val md_theme_light_onError = Color(0xFFffffff)
    val md_theme_light_onErrorContainer = Color(0xFF410001)
    val md_theme_light_background = Color(0xFFfcfcff)
    val md_theme_light_onBackground = Color(0xFF1a1c1e)
    val md_theme_light_surface = Color(0xFFfcfcff)
    val md_theme_light_onSurface = Color(0xFF1a1c1e)
    val md_theme_light_surfaceVariant = Color(0xFFdee3eb)
    val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
    val md_theme_light_outline = Color(0xFF72777e)
    val md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
    val md_theme_light_inverseSurface = Color(0xFF2f3032)
    val md_theme_light_inversePrimary = Color(0xFF92ccff)
    val md_theme_light_shadow = Color(0xFF000000)

    val md_theme_dark_primary = Color(0xFF92ccff)
    val md_theme_dark_onPrimary = Color(0xFF003353)
    val md_theme_dark_primaryContainer = Color(0xFF004a75)
    val md_theme_dark_onPrimaryContainer = Color(0xFFcbe5ff)
    val md_theme_dark_secondary = Color(0xFFb8c8da)
    val md_theme_dark_onSecondary = Color(0xFF233240)
    val md_theme_dark_secondaryContainer = Color(0xFF394857)
    val md_theme_dark_onSecondaryContainer = Color(0xFFd5e4f6)
    val md_theme_dark_tertiary = Color(0xFFd2bfe6)
    val md_theme_dark_onTertiary = Color(0xFF382a4a)
    val md_theme_dark_tertiaryContainer = Color(0xFF4f4161)
    val md_theme_dark_onTertiaryContainer = Color(0xFFefdbff)
    val md_theme_dark_error = Color(0xFFffb4a9)
    val md_theme_dark_errorContainer = Color(0xFF930006)
    val md_theme_dark_onError = Color(0xFF680003)
    val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
    val md_theme_dark_background = Color(0xFF1a1c1e)
    val md_theme_dark_onBackground = Color(0xFFe2e2e5)
    val md_theme_dark_surface = Color(0xFF1a1c1e)
    val md_theme_dark_onSurface = Color(0xFFe2e2e5)
    val md_theme_dark_surfaceVariant = Color(0xFF41474d)
    val md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
    val md_theme_dark_outline = Color(0xFF8c9198)
    val md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
    val md_theme_dark_inverseSurface = Color(0xFFe2e2e5)
    val md_theme_dark_inversePrimary = Color(0xFF00639a)
    val md_theme_dark_shadow = Color(0xFF000000)

    val seed = Color(0xFF81b2df)
    val error = Color(0xFFba1b1b)
}
